### ISSUE TITLE
Point3D and Vector3D don't handle string input

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug-geometry#25]
I expect Point3D to either give an error or convert string inputs to float. Currently it does neither.

```python
import ladybug_geometry.geometry3d.pointvector as pv

point = pv.Point3D('10', '10', '10')
print(point)
```

```
    return 'Point3D (%.2f, %.2f, %.2f)' % (self.x, self.y, self.z)
TypeError: must be real number, not str
```

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

In the tests that I ran, casting to a new float for every single point severely decreases the performance when creating things like mesh grids or meshes from Rhino curved geometry.  I imagine that this is also the reason why euclid did not put such checks into its point objects.

Are you sure that casting to float isn't something that you can handle outside of the Point3D class?

Isn't duck-typing is sufficient here and isn't that error message enough to figure out what is wrong?

**Comment by mostaphaRoudsari** [comment]
Hey @chriswmackey,

I hear you and I think it is fine to keep it like this.

> Are you sure that casting to float isn't something that you can handle outside of the Point3D class?

That's what I have been doing but I think the better question is where should this conversion being taken care of? I personally think inside the geometry library but in my case it is totally possible to do the type checking outside.

> Isn't duck-typing is sufficient here and isn't that error message enough to figure out what is wrong?

The error is fine but I think it should be raised when one creates a point with strings. Right now you won't get an error until later when you use a method.

I close this for now and we will see if someone else opens a similar issue in the future. Then we can discuss again if it makes sense to add support for string inputs. Also if at some point we stop supporting python 2 we will have more elegant solutions to address this with builtin typing.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

I have a correction to make about this.  I thought the performance was really suffering from the float assertion but I now think that it had more to do with the (now abandoned) idea of having mutable and immutable versions of the Point3D object.  Now that everything is immutable, the point creation process is much smoother and adding in a cast to float really doesn't affect the performance.

For creating a ladybug mesh grid with 8760 cells and converting it to a Rhino mesh, the change in performance with IronPython is really small (70ms with the float casting and 47ms without it).  And, if that's the change in IronPython, I'm sure that it is even smaller with Python 3.

So I will implement some float casting within the Point2D and Point3D objects. You are right that it is better to take care of it here if we can and it doesn't kill the performance.

**Comment by chriswmackey** [comment]
I guess I reopened it only to immediately close it.  It's taken care of here:
https://github.com/ladybug-tools/ladybug-geometry/pull/33
