### ISSUE TITLE
Add Mesh3D.from_stl method

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug-geometry#338]
This is going to be important for integration with CFD workflows in particular. It seems stl format is all in human-readable text.  So this should hopefully be pretty straightforward.

**Comment by mostaphaRoudsari** [comment]
This might help as a sample:

https://github.com/proverbialsunrise/pySTL/blob/6afb180e14ee13fe313028cc9d9efa9104f7b1fe/pySTL.py#L95-L188
