### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/ladybug-geometry#50]
Documentation needs cleaned up in the following manner:
* Put any ASCII art in a .. code-block:: shell
* Put any dictionaries in from_dict methods in a .. code-block:: json
* Move all descriptions in init to be on the class itself.
* Get child classes to display documentation of their children
* Get the returns to display correctly (not bolded)
* Get properties and methods to be organized groupwise
* Get the navigation bar to not bleed onto the docs

@chriswmackey and @santiagogaray I've created this issue here so we can refer to it the in final commit to Santiago's kickass PR 😄

**Comment by chriswmackey** [comment]
Thank you @AntoineDao . I think we may copy this issue to all of the other repos once we get the PR merged.

**Comment by chriswmackey** [comment]
I think we can now close out this issue here now that @santiagogaray 's PR has been merged.  BTW, I updated the [original issue in the ladybug-core repo](https://github.com/ladybug-tools/ladybug/issues/158) with all of the insights that we have gained here from @santiagogaray 's work.
