### ISSUE TITLE
Add straight skeleton methods to Polygon2D class

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug-geometry#53]
The current plan to implement core/perimeter zoning in places like honeybee and dragonfly is to have the methods related to the straight skeleton geometric calculations here in this repo under the [Polygon2D class](https://github.com/ladybug-tools/ladybug-geometry/blob/master/ladybug_geometry/geometry2d/polygon.py).

You can see that @saeranv did an awesome job [implementing a straight skeleton method in honeybee-legacy](https://github.com/ladybug-tools/honeybee-legacy/blob/master/src/Honeybee_SplitFloor2ThermalZones.py#L112-L1896). Much of the custom code within that component can now be replaced with the methods of other classes in this repo (I am thinking the vector math in particular). Additionally, the code in honeybee-legacy only works for convex polygons but the underlying method that @saeranv is using (the [Aichholzer  straight skeleton method](http://www.jucs.org/jucs_1_12/a_novel_type_of)) does not have this restriction. Saeran has confirmed that the inability to handle concave forms is the result of a yet unidentified bug in his original code and so we should be able to solve it here.

Given the complexity of straight skeletons, it might be best is @saeranv or myself (@chriswmackey ) handle this translation.  If anyone else has good knowledge of straight skeletons, please feel free to take up the mantle here.

**Comment by saeranv** [comment]
@chriswmackey  

Sorry for leaving this unfinished for so long. What's the timeline for this implementation? I'm unfortunately extremely busy until xmas break, but I could tackle this then, if you can afford to wait. 

S

**Comment by chriswmackey** [comment]
@saeranv ,
There's not a major rush on this and I mostly posted the issue in order to record how I thought it should be best implemented.  I was thinking that it would be nice to have it for the official release of Dragonfly that we have planned for the Spring, which will be for both urban energy and the UWG.  So, if you wanted to tackle it soon after the xmas break, I think that would work well.

**Comment by chriswmackey** [comment]
I think that we can probably close out of this one now that ladybug_geometry_polyskel exists. @saeranv , do you agree?

**Comment by saeranv** [comment]
@chriswmackey Agreed, done.
