### ISSUE TITLE
Add a staticmethod to Polygon2D to perform a 1D intersection of segments with one another

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug-geometry#57]
Particularly within Dragonfly, there will be many cases where we have a bunch of rooms represented by 2D polygons like so:
![image](https://user-images.githubusercontent.com/5567574/66066818-46b8c200-e518-11e9-8920-7dede236647c.png)

In order to get the adjacent walls between these 2D rooms to match one another, we should have a `staticmethod ` in the [Polygon2D](https://github.com/ladybug-tools/ladybug-geometry/blob/master/ladybug_geometry/geometry2d/polygon.py) class that intersects each segment of a polygon with another to  ensure adjacent segments are matching in length. Essentially, this would take a situation like this:
```
                             |           1          |
                            A|______________________|C
                             |          B|          |
                             |           |          |
                             |     2     |     3    |
```
... and add split segment AC of polygon 1 into two segments in order to match the adjacent teo polygons.

We [already have a method to perform 1D intersections of one line segment with another here](https://github.com/ladybug-tools/ladybug-geometry/blob/master/ladybug_geometry/intersection2d.py#L10-L33). The [closest_point2d_on_line2d](https://github.com/ladybug-tools/ladybug-geometry/blob/master/ladybug_geometry/intersection2d.py#L157-L174) might also be useful.

In any case, because these methods are already here, adding this staticmethod should be pretty straightforward.

**Comment by DatHydroGuy** [comment]
Hi.  I'd be interested in tackling this issue for you.  Can you just clarify that my understanding of your expectations is correct, please?

- You would like the new method to take two polygons as arguments
- The new method would return the two modified polygons with any extra vertices inserted
- The vertices of the returned polygons should be in the same order (clockwise / counter-clockwise)

Many thanks

**Comment by chriswmackey** [comment]
We can close this issue now that it has been addressed by @DatHydroGuy .
