### ISSUE TITLE
Implement 2D polygon offset method

### ISSUE THREAD

**Issue by saeranv** [ladybug-tools/ladybug-geometry#86]
Once we finish implementing the straight skeleton method (#53), the next step is generate thermal zones from the skeleton by offsetting the exterior edges, and intersecting them with the skeleton methods. This was done with the Rhino library in the original version of the thermal zone splitter, so isn't available for our ladybug-geometry version.

I'm not sure yet a good way to implement this will be. The brute force way would be to just apply translations and intersections to the outer LineSegment2Ds, but I'd like to do some googling first to see if there might be a more efficient way to do this.

Potential method? https://link.springer.com/article/10.1007/s00170-005-0013-1

**Comment by theo-armour** [comment]
Over the years,  have worked a number of times with offset lines. Here is an example from 2017:

https://www.ladybug.tools/spider/cookbook/03-line-with-parallel-offset/line-with-parallel-offset.html

![image](https://user-images.githubusercontent.com/547626/73723592-3d19b380-46de-11ea-8198-0ca3e46ebfc9.png)

With other elated examples here:

https://www.ladybug.tools/spider/#cookbook/README.md

Looking at the code, there are opportunities for simplifying and streamlining. If you can read the code and have specific use cases, let me know and I will build more demos.

**Comment by saeranv** [comment]
@theo-armour Cool, can you point me towards the code? That link is sending me to a blank page.

**Comment by theo-armour** [comment]
@saeranv 

>  Cool, can you point me towards the code? 

I have added details about the source to the original post.

> That link is sending me to a blank page.

Which link is broken for you?

**Comment by saeranv** [comment]
@theo-armour this link sends me to a blank page: https://www.ladybug.tools/spider/cookbook/03-line-with-parallel-offset/line-with-parallel-offset.html . 

Thanks for providing the code. It looks like something I should be able to reproduce in python quickly and test out.

**Comment by theo-armour** [comment]
@saeranv 

>>  this link sends me to a blank page: https://www.ladybug.tools/spider/cookbook/03-line-with-parallel-offset/line-with-parallel-offset.html .

I have opened the above link with latest Chrome, Edge and Firefox on W10, Chrome on Chromebook, Chrome on Android phone and the above polygon with offset as illustrated above appears.

Questions

1. What is your set up?
2. What does the JavaScript Developer Console report (Control/Command-Shift-J or F12)?
3. Does this script load: https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/ ??

**Comment by saeranv** [comment]
@theo-armour , might be something on my end, then. 

1. I'm just using a regular Chrome browser.
2. 
![image](https://user-images.githubusercontent.com/1685956/74167042-9f4e4900-4bf5-11ea-8d3e-3c4695c441da.png)
3. Nope.

**Comment by theo-armour** [comment]
It looks like your system is not supporting [WebGL]( https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API )

Verify here:

* https://get.webgl.org/
* https://webglreport.com/?v=2

Either you have a very, very old system of or have turned off WebGL support somewhere

**Comment by saeranv** [comment]
@theo-armour thanks for figuring that out! I'm going to have to look into it for sure. 

Returning to the question of offsetting, I've had some time to do some research on state-of-the-art methods, and I think we can implement a modified version of your method that will be a bit more robust against edge cases. 

This paper here is a good survey on state-of-art for this question: http://fcacciola.50webs.com/Offseting%20Methods.htm. It's old (2003) but seems to confirm the general gist of what I'm seeing in more recent publications as well.  The paper defines the technique you are using as a "locality-based" approach, where every polygon edge is offset, and then <i>locally</i> intersected. The biggest disadvantage of this approach is that offsetting is a combinatoric problem (in certain cases you will have multiple options to intersect and join edges) and locality-based methods require complex heuristics to figure out which option is correct. 

Here's an example of this issue, where I've outlined a case where a single line needs to be split into two to create two islands (or disjoint polygons) in the center:
![image](https://user-images.githubusercontent.com/1685956/74289513-3651f880-4cfd-11ea-8a1b-a912f683b631.png)
 
Let me know if I'm misunderstanding your code, but I think this problem might apply to your method. 

There's a couple of algorithms they review in the paper that can handle these edge conditions, generally termed "structural-based" methods, where the offset curves are constrained by a geometric structure that resolves the intersection for us. Lucky for us, the straight skeleton (#53) provides such a geometric structure. I actually didn't realize this before hand, but it makes sense, as the straight skeleton of a polygon is essentially the geometric result of a maximum offset. Thus, the closed polygons from a straight skeleton, should provide the bounds for any offset edge, and in doing so intrinsically provide the correct topological solution. I've started on an initial prototype that kind of shows the relationship between a straight skeleton and offset curves:

![image](https://user-images.githubusercontent.com/1685956/74290286-67cbc380-4cff-11ea-9921-5e7887eadc0b.png)

So I think my approach will be to use your method as the base, and improve it's robustness, with a ladybug's straight skeleton method.

**Comment by saeranv** [comment]
@theo-armour, also I can confirm that this page not working: https://www.ladybug.tools/spider/cookbook/03-line-with-parallel-offset/line-with-parallel-offset.html, definitly had something to do with my system. I recently just moved to a new laptop and that link is working perfectly.

**Comment by theo-armour** [comment]
@saeranv 

Listening to other communications, it seems that you have a good handle on this project.

So shall we close this issue?

**Comment by saeranv** [comment]
@theo-armour Agreed, done!
